### PR TITLE
Similar to https://github.com/ubports/indicator-power/pull/23

### PR DESCRIPTION
**Pull request by nfsprodriver**

### CODE REVIEW

**Review by Flohack74 — APPROVED** [review]

**Comment by Flohack74** [comment]
We should test if the translation for "Flashlight" landed in today´s devel btw ;)

**Comment by cibersheep** [comment]
I don't know how to test this
- Flashlight is translated in N5 (RC)

**Comment by Flohack74** [comment]
@cibersheep well thats the datetime-indicator, not power where the flashlight would be. You should see no more "Time and Date" as indicator title...

**Comment by Bolly** [comment]
BQM10FHD on RC.
Language Spanish:
Date & Time -> Fecha y hora

Work for me.

**Comment by cibersheep** [comment]
Ouh. Translated strings.

(Keyboard Layout missing to translate ;D)

**Pull request merged**
